spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  cloud:
    aws:
      s3:
        bucket: kuji-image # 💡 설정 완료!
      region:
        static: eu-north-1

  config:
    import: optional:classpath:application-secret.yml
server:
  port: 8080
  address: 0.0.0.0

jwt:
  # 💡 우리 서버만의 비밀키 (환경변수 또는 application-secret.yml 주입)
  secret: ${JWT_SECRET_KEY}
  # 💡 토큰 유효 시간 (밀리초 단위, 30분 = 1800000)
  #expiration: 1800000
  expiration: 300000
  # 💡 리프레시 토큰 유효 시간 (밀리초 단위, 14일 = 1209600000)
  refresh-expiration: 1209600000

file:
  upload-dir: uploads

toss:
  # 💡 [필수] 토스페이먼츠 시크릿 키 (환경변수 또는 application-secret.yml 주입)
  secret-key: ${TOSS_SECRET_KEY}
aligo:
  api-key: ${ALIGO_API_KEY:mock}
  user-id: ${ALIGO_USER_ID:mock}
  sender: ${ALIGO_SENDER:01022210106}
